
/* errors (#defines) */

#define CANT_OPEN_LOAD_FILE       (WARNING_ERROR | 0x1001)
#define INPUT_FILE_ERROR          (WARNING_ERROR | 0x1002)
#define OUTPUT_FILE_ERROR         (WARNING_ERROR | 0x1003)
#define FORMAT_NOT_SUPPORTED      (WARNING_ERROR | 0x1004)
#define NO_PICTURE_IN_FILE        (WARNING_ERROR | 0x1005)
#define COULDNT_CONVERT_FROM_JPEG (WARNING_ERROR | 0x1006)
#define COULDNT_CONVERT_TO_JPEG   (WARNING_ERROR | 0x1007)
