
/* texts (german version) */

  TXT_WIDTH_COL_SPC	     ,"Breite: ",
  TXT_LOADING_RGBFILES	     ,"Lade separate R,G,B-Dateien",
  TXT_SAVING_RGBFILES	     ,"Speichere separate R,G,B-Dateien",
  TXT_PCXPICTURE	     ,"PCX - Bild",
  TXT_WIDTH_D		     ,"Breite: %d",
  TXT_HEIGHT_D		     ,"Höhe: %d",
  TXT_COLORS_D		     ,"%d Farben",
  TXT_VERSION_S 	     ,"Version: %s",
  TXT_VERSION_D 	     ,"Version: %d",
  TXT_VERSION_DDD	     ,"Version: %d.%x%x",
  TXT_VER25_WITH_PAL	     ,"2.5 mit Paletteninformation",
  TXT_VER25_WITHOUT_PAL      ,"2.5 ohne Paletteninformation",
  TXT_VER_WIN_WITHOUT_PAL    ,"Windows ohne Paletteninformation",
  TXT_COMPRESSION_S	     ,"Kompression: %s",
  TXT_NONE		     ,"keine",
  TXT_XRESOLUTION_D_DPI      ,"Horizontale Auflösung: %d dpi",
  TXT_YRESOLUTION_D_DPI      ,"Vertikale Auflösung: %d dpi",
  TXT_COLORPLANES_D	     ,"Farbebenen: %d",
  TXT_BITSPERPIXEL_D	     ,"Bits pro Pixel: %d",
  TXT_COLORMODE_S	     ,"Farbmodus: %s",
  TXT_ITS_COLOR 	     ,"farbig",
  TXT_GREYSCALE 	     ,"Graustufen",
  TXT_READING_PCX	     ,"Lese PCX - Bild",
  TXT_SAVING_PCX	     ,"Speichere PCX - Bild",
  TXT_GIF_INTERLACED_IMAGE   ,"Bild im Interlaced-Modus",
  TXT_GIF_RASTER_IMAGE	     ,"Bild im Raster-Modus",
  TXT_LOADING_GLOBAL_COLORMAP,"Lade die globale Farbtabelle",
  TXT_S_IMAGE		     ,"Bild im %s Modus",
  TXT_POSITION_DD	     ,"Position: %d,%d",
  TXT_LOCAL_COLORMAP_EXISTS  ,"lokale Farbtabelle vorhanden",
  TXT_NO_LOCAL_COLORMAP      ,"Keine lokale Farbtabelle",
  TXT_GLOBAL_COLORMAP_EXISTS ,"globale Farbtabelle vorhanden",
  TXT_NO_GLOBAL_COLORMAP     ,"Keine globale Farbtabelle",
  TXT_SCREENWIDTH_D	     ,"Bildschirmbreite: %d",
  TXT_SCREENHEIGHT_D	     ,"Bildschirmhöhe: %d",
  TXT_WIN3X_BMP 	     ,"Windows 3.x Bitmap-Format (BMP)",
  TXT_UNKNOWN		     ,"unbekannt",
  TXT_XRESOLUTION_D_PIXM     ,"Horizontale Auflösung: %d Pixels/m",
  TXT_YRESOLUTION_D_PIXM     ,"Vertikale Auflösung: %d Pixels/m",
  TXT_COLORSUSED_D	     ,"%d benutzte Farben",
  TXT_IMPORTANTCOLORS_D      ,"%d wichtige Farben",
  TXT_LOADING_BMP	     ,"Lade BMP - Bild",
  TXT_IFF_S_IMAGE	     ,"IFF - %s Bild",
  TXT_BITPLANES_DSS	     ,"Bitplanes : %d %s%s",
  TXT_TRUECOLOR 	     ,"(Echtfarben)",
  TXT_INCL_GENLOCKPLANE      ,"inklusive einer Genlock-Ebene",
  TXT_CAMG_EXISTS	     ,"CAMG-Chunk vorhanden",
  TXT_CAMG_DOESNT_EXIST      ,"CAMG-Chunk nicht vorhanden",
  TXT_IMAGINE_COMPRESSION    ,"Kompressionsalgorithmus von 'Imagine'",
  TXT_MASKING_S 	     ,"Maskierung: %s",
  TXT_TRANSPARENT_COLOR      ,"transparente Farbe",
  TXT_MASKPLANE 	     ,"zusätzliche Masken-Ebene",
  TXT_LASSOMASK 	     ,"Lasso-Maske",
  TXT_ASPECT_DD 	     ,"Seitenverhältnis: %d:%d",
  TXT_PAGESIZE_DD	     ,"Seitengröße: %dx%d",
  TXT_LOADING_ILBM	     ,"Lade ILBM - Bild",
  TXT_LOADING_ILBM_PBM	     ,"Lade ILBM-PBM - Bild",
  TXT_SAVING_ILBM	     ,"Speichere als ILBM - Bild",
  TXT_COLOR_D_DDD	     ,"Farbe %3d: %3d %3d %3d\n",
  TXT_MORE_REGS_THAN_COLORS  ,"Genug Farbregister vorhanden.",
  TXT_BUILDING_HISTOGRAMM    ,"Erstelle Farb-Histogramm.",
  TXT_D_DIFFERENT_COLORS     ,"%d unterschiedliche Farben gefunden.",
  TXT_SCANNING_CUBE	     ,"Durchsuche den Farbwürfel.",
  TXT_BITMAP_TO_CLUT	     ,"Konvertiere Bitmap zu CLUT-Bitplanes.",
  TXT_BITMAP_TO_HAM	     ,"Konvertiere Bitmap zu HAM-Bitplanes.",
  TXT_CLUT_TO_24BIT	     ,"Konvertiere CLUT-Bitmap zu 24Bit.",
  TXT_LOADING_RGBN8	     ,"Lade RGBN/RGB8 - Bild",
  TXT_GEM_IMAGE 	     ,"GEM Bild (IMG)",
  TXT_PATTERNLENGTH_D	     ,"Muster-Länge: %d",
  TXT_PIXELWIDTH_D_YM	     ,"Pixelbreite: %d Mikrometer",
  TXT_PIXELHEIGHT_D_YM	     ,"Pixelhöhe: %d Mikrometer",
  TXT_LOADING_IMG	     ,"Lade IMG - Bild",
  TXT_PROGRESS_INDICATOR     ,"Verlaufs-Anzeige",
  TXT_OPERATION_MESSAGES     ,"Tätigkeits-Meldungen",
  TXT_CONVERSION_PROGRESS    ,"Konvertierung läuft...",
  TXT_LOAD		     ,"Laden",
  TXT_INPUT_FORMAT	     ,"Eingabeformat:",
  TXT_SAVE		     ,"Speichern",
  TXT_OUTPUT_FORMAT	     ,"Ausgabeformat:",
  TXT_SIZE		     ,"Größe",
  TXT_CUSTOM		     ,"ändern",
  TXT_INTERPOLATED	     ,"interpoliert",
  TXT_WIDTH		     ,"Breite:",
  TXT_HEIGHT		     ,"Höhe:",
  TXT_TRANSFORM 	     ,"umformen",
  TXT_FLIP		     ,"spiegeln:",
  TXT_FLIP_NOTHING	     ,"nicht",
  TXT_FLIP_H		     ,"horizontal",
  TXT_FLIP_V		     ,"vertikal",
  TXT_FLIP_HV		     ,"hor. & ver.",
  TXT_ROTATE		     ,"drehen:",
  TXT_ROT_NOTHING	     ,"nicht",
  TXT_ROT_PLUS90	     ,"+90 Grad",
  TXT_ROT_MINUS90	     ,"-90 Grad",
  TXT_COLORS		     ,"Farben",
  TXT_COLORMODE 	     ,"Farbmodus:",
  TXT_COLORS_COL	     ,"Farben:",
  TXT_DITHERING 	     ,"Rasterung:",
  TXT_DITHER_NONE	     ,"keine",
  TXT_EFFECTS		     ,"Effekte:",
  TXT_EFX_NONE		     ,"keine",
  TXT_EFX_BW		     ,"Schwarz/Weiß",
  TXT_EFX_INV		     ,"Negativ",
  TXT_EFX_INV_BW	     ,"Negativ & SW",
  TXT_EFX_RED_FILTER	     ,"roter Filter",
  TXT_EFX_GREEN_FILTER	     ,"grüner Filter",
  TXT_EFX_BLUE_FILTER	     ,"blauer Filter",
  TXT_EFX_YELLOW_FILTER      ,"gelber Filter",
  TXT_EFX_MAGENTA_FILTER     ,"violetter Filter",
  TXT_EFX_CYAN_FILTER	     ,"türkiser Filter",
  TXT_BRIGHTNESS	     ,"Helligkeit",
  TXT_CONTRAST		     ,"Kontrast",
  TXT_CONVERT		     ,"Konvertieren",
  TXT_INFOS		     ,"Bild-Infos",
  TXT_WINDOW_TITLE	     ,"Bildformat-Konverter  © Dirk Farin",
  TXT_REDUCED_RESOLUTION     ,"    reduzierte Auflösung",
  TXT_MULTI_PAGE_PICTURE     ,"    mehrseitiges Bild",
  TXT_TRANSPARENT_MASK	     ,"    Durchlässigkeits-Maske",
  TXT_NOTHING_SPECIAL	     ,"    nichts besonderes",
  TXT_FULL_RES_PICTURE	     ,"Bild mit voller Auflösung",
  TXT_REDU_RES_PICTURE	     ,"Bild mit reduzierter Auflösung",
  TXT_SINGLE_PAGE_PICTURE    ,"Bild auf einzelner Seite",
  TXT_UNCOMPRESSED	     ,"unkomprimiert",
  TXT_UNCOMPRESSED_WORDALIGN ,"unkomprimiert (an Wortgrenze ausgerichtet)",
  TXT_MINSAMPLE_WHITE	     ,"MinSampleValue = Weiß",
  TXT_MINSAMPLE_BLACK	     ,"MinSampleValue = Schwarz",
  TXT_MINSAMPLE_RGB_DARK     ,"RGB MinSampleValue = Dunkel",
  TXT_PALETTE_COLOR	     ,"Farbtabelle",
  TXT_TRANSPARENCY_MASK      ,"Transparenz-Maske",
  TXT_BILEVEL		     ,"Bilevel Bild",
  TXT_GREYSCALE_TO_BW	     ,"zu Schwarz/Weiß konvertierte Graustufen",
  TXT_GREYSCALE_TO_BW_ERRDIF ,"mittels Fehlerverteilung zu Schwarz/Weiß konvertierte Graustufen",
  TXT_MSB_LSB		     ,"vom MSB zum LSB",
  TXT_LSB_MSB		     ,"vom LSB zum MSB",
  TXT_ORIENTATION_S	     ,"Orientierung: erste Bitmap-Zeile ist %s",
  TXT_EDGE_TLR		     ,"obere Kante, von links nach rechts",
  TXT_EDGE_TRL		     ,"obere Kante, von rechts nach links",
  TXT_EDGE_BRL		     ,"untere Kante, von rechts nach links",
  TXT_EDGE_BLR		     ,"untere Kante, von links nach rechts",
  TXT_EDGE_LTB		     ,"linke Kante, von oben nach unten",
  TXT_EDGE_RTB		     ,"rechte Kante, von oben nach unten",
  TXT_EDGE_RBT		     ,"rechte Kante, von unten nach oben",
  TXT_EDGE_LBT		     ,"linke Kante, von unten nach oben",
  TXT_PLANAR_NOBITPLANES     ,"keine Bitplanes (Daten für einen Punkt zusammenhängend)",
  TXT_PLANAR_BITPLANES	     ,"Bitplanes",
  TXT_4SPC_UNCOMPRESSED      ,"    unkomprimiert",
  TXT_4SPC_FILLBITSATEND     ,"    Füll-Bits wurden am Ende der Zeile eingefügt",
  TXT_4SPC_NONE 	     ,"    keine",
  TXT_NO_INFORMATION	     ,"keine Information",
  TXT_NO_PREDICTION	     ,"keine Prediction",
  TXT_LOADING_TIFF_BW	     ,"Lade TIFF Schwarz/Weiß - Bild",
  TXT_LOADING_TIFF_256	     ,"Lade TIFF 256 Farben - Bild",
  TXT_LOADING_TIFF_16	     ,"Lade TIFF 16 Farben - Bild",
  TXT_LOADING_TIFF_BW_CCITT3 ,"Lade TIFF Schwarz/Weiß, CCITT3-komprimiertes Bild",
  TXT_LOADING_TIFF_BW_PACKBIT,"Lade TIFF Schwarz/Weiß, PackBit-komprimiertes Bild",
  TXT_LOADING_TIFF_256_PACKBIT,"Lade TIFF PackBit-komprimiertes 256 Farben - Bild",
  TXT_LOADING_TIFF_LZW_RGB   ,"Lade TIFF LZW-komprimiertes RGB - Bild",
  TXT_LOADING_TIFF_LZW_MONO  ,"Lade TIFF LZW-komprimiertes Schwarz/Weiß - Bild",
  TXT_LOADING_TIFF_LZW_256   ,"Lade TIFF LZW-komprimiertes 256 Farben - Bild",
  TXT_LOADING_TIFF_RGB	     ,"Lade TIFF unkomprimiertes RGB - Bild",
  TXT_DOFLIP_H		     ,"Spiegele das Bild horizontal.",
  TXT_DOFLIP_V		     ,"Spiegele das Bild vertikal.",
  TXT_TO_BW		     ,"Konvertiere nach Schwarz/Weiß.",
  TXT_FILTERING 	     ,"Filtere Farben.",
  TXT_INVERTING 	     ,"Invertiere das Bild.",
  TXT_BRI_CON		     ,"Ändere Helligkeit und Kontrast.",
  TXT_RESIZING		     ,"Verändere die Größe des Bildes.",
  TXT_INTERPOL_RESIZE	     ,"Verändere die Größe des Bildes mittels Interpolation.",
  TXT_ROTATING_90	     ,"Rotiere um 90 Grad",
  TXT_ROTATING_M90	     ,"Rotiere um -90 Grad",
  TXT_LOADREQ_TITLE	     ,"Datei laden",
  TXT_SAVEREQ_TITLE	     ,"Datei speichern",
  TXT_REQUESTER_OK	     ,"OK",
  TXT_REQUESTER_CANCEL	     ,"Abbruch",
  TXT_SAVING_POSTSCRIPT      ,"Speichere als Postscript-Datei",
  TXT_POST_XPOS 	     ,"X-Pos:",
  TXT_POST_YPOS 	     ,"Y-Pos:",
  TXT_POST_WIDTH	     ,"Breite:",
  TXT_POST_HEIGHT	     ,"Höhe:",
  TXT_POST_POSWIN_TITLE      ,"Position angeben:",
  TXT_LOADING_JPEG	     ,"Lade JPEG (JFIF) - Bild",
  TXT_SAVING_JPEG	     ,"Speichere JPEG (JFIF) - Bild",
  TXT_JPEG_QUALITY	     ,"Qualität:",
  TXT_JPEG_PARAMETERS	     ,"JPEG-Einstellungen",
  TXT_FAST_FLOYD	     ,"schneller Floyd-Steinberg",
  TXT_COL_GRAYSCALE	     ,"Graustufen",
  TXT_ABOUT		     ,"Prog.Infos",
  TXT_UNREGISTERED	     ,"( unregistriert ! )",
  TXT_DO_REGISTER_1	     ,"Vergessen Sie nicht, das Programm",
  TXT_DO_REGISTER_2	     ,"registrieren zu lassen !",
  TXT_LOADING_TARGA	     ,"Lade Targa-Bild",
  TXT_SAVING_GIF	     ,"Speichere GIF-Bild",
  TXT_TARGA_INFOS	     ,"Targa Bild-Infos",
  TXT_TARGA_NO_CMAP	     ,"keine Farbtabelle enthalten",
  TXT_TARGA_CMAP_INCL	     ,"Farbtabelle enthalten",
  TXT_TARGA_UNKN_CMAP	     ,"unbekannter Farbtabellen-Typ",
  TXT_TARGA_NO_IMAGE	     ,"kein Bild enthalten",
  TXT_TARGA_UNCOMPR_CMAP     ,"unkomprimiert, Farbtabelle",
  TXT_TARGA_UNCOMPR_TRUECOL  ,"unkomprimiert, Echtfarben",
  TXT_TARGA_UNCOMPR_BW	     ,"unkomprimiert, schwarz-weiss",
  TXT_TARGA_RLE_CMAP	     ,"lauflängenkomprimiert, Farbtabelle",
  TXT_TARGA_RLE_TRUECOL      ,"lauflängenkomprimiert, Echtfarben",
  TXT_TARGA_RLE_BW	     ,"lauflängenkomprimiert, schwarz-weiss",
  TXT_TARGA_FIRST_CMAP_ENTRY ,"erster Farbtabelleneintrag: %d",
  TXT_TARGA_CMAP_ENTRIES     ,"Anzahl der Farbtabelleneinträge: %d",
  TXT_TARGA_BITS_PER_ENTRY   ,"Bits pro Farbtabelleneintrag: %d",
  TXT_TARGA_XORIGIN	     ,"Linke Ecke: %d",
  TXT_TARGA_YORIGIN	     ,"Untere Ecke: %d",
  TXT_TARGA_WIDTH	     ,"Breite: %d",
  TXT_TARGA_HEIGHT	     ,"Höhe: %d",
  TXT_TARGA_PIXELDEPTH	     ,"Bits pro Pixel: %d",
  TXT_TARGA_BOTLEFT	     ,"links unten",
  TXT_TARGA_BOTRIGHT	     ,"rechts unten",
  TXT_TARGA_TOPLEFT	     ,"links oben",
  TXT_TARGA_TOPRIGHT	     ,"rechts oben",
  TXT_TARGA_ORIGIN	     ,"Nullpunkt: %s",
  TXT_TARGA_ALPHA_BITS	     ,"Bits des Alpha-Channels: %d",
  TXT_GRAPHIC_CONTROL_EXISTS	   , "Graphic Control Extension Block vorhanden",
  TXT_GRAPHIC_CONTROL_CORRUPT	   , "Graphic Control-Block ungültig",
  TXT_GRAPHIC_CONTROL_TRANSCOLOR_D , "Transparente Farbe: %d",

