/*******************************************************************************
 *
 * Copyright (C) 1993  Dirk Farin  <dirk.farin@gmail.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 ********************************************************************************/

/* texts (english version) */

  TXT_WIDTH_COL_SPC	     ,"Width: ",
  TXT_LOADING_RGBFILES	     ,"Loading r,g,b-files",
  TXT_SAVING_RGBFILES	     ,"Saving r,g,b-files",
  TXT_PCXPICTURE	     ,"PCX - picture",
  TXT_WIDTH_D		     ,"Width: %d",
  TXT_HEIGHT_D		     ,"Height: %d",
  TXT_COLORS_D		     ,"%d colors",
  TXT_VERSION_S 	     ,"Version: %s",
  TXT_VERSION_D 	     ,"Version: %d",
  TXT_VERSION_DDD	     ,"Version: %d.%x%x",
  TXT_VER25_WITH_PAL	     ,"2.5 with palette-information",
  TXT_VER25_WITHOUT_PAL      ,"2.5 without palette-information",
  TXT_VER_WIN_WITHOUT_PAL    ,"Windows without palette-information",
  TXT_COMPRESSION_S	     ,"Compression: %s",
  TXT_NONE		     ,"none",
  TXT_XRESOLUTION_D_DPI      ,"X-resolution: %d dpi",
  TXT_YRESOLUTION_D_DPI      ,"Y-resolution: %d dpi",
  TXT_COLORPLANES_D	     ,"Colorplanes: %d",
  TXT_BITSPERPIXEL_D	     ,"Bits per pixel: %d",
  TXT_COLORMODE_S	     ,"Colormode: %s",
  TXT_ITS_COLOR 	     ,"color",
  TXT_GREYSCALE 	     ,"grey-scale",
  TXT_READING_PCX	     ,"Reading PCX-picture",
  TXT_SAVING_PCX	     ,"Saving PCX-picture",
  TXT_GIF_INTERLACED_IMAGE   ,"interlaced-mode picure",
  TXT_GIF_RASTER_IMAGE	     ,"raster-mode picure",
  TXT_LOADING_GLOBAL_COLORMAP,"Loading global colormap",
  TXT_S_IMAGE		     ,"%s image",
  TXT_POSITION_DD	     ,"Position: %d,%d",
  TXT_LOCAL_COLORMAP_EXISTS  ,"Local Colormap exists",
  TXT_NO_LOCAL_COLORMAP      ,"Local Colormap does not exist",
  TXT_GLOBAL_COLORMAP_EXISTS ,"Global Colormap exists",
  TXT_NO_GLOBAL_COLORMAP     ,"Global Colormap does not exist",
  TXT_SCREENWIDTH_D	     ,"Screen width: %d",
  TXT_SCREENHEIGHT_D	     ,"Screen height: %d",
  TXT_WIN3X_BMP 	     ,"Windows 3.x bitmap-format (BMP)",
  TXT_UNKNOWN		     ,"unknown",
  TXT_XRESOLUTION_D_PIXM     ,"X-resolution: %d pixels/m",
  TXT_YRESOLUTION_D_PIXM     ,"Y-resolution: %d pixels/m",
  TXT_COLORSUSED_D	     ,"%d used colors",
  TXT_IMPORTANTCOLORS_D      ,"%d important colors",
  TXT_LOADING_BMP	     ,"Loading BMP - picture",
  TXT_IFF_S_IMAGE	     ,"IFF - %s picture",
  TXT_BITPLANES_DSS	     ,"Bitsplanes : %d %s%s",
  TXT_TRUECOLOR 	     ,"(TrueColors)",
  TXT_INCL_GENLOCKPLANE      ,"including one genlock-plane",
  TXT_CAMG_EXISTS	     ,"CAMG-chunk exists",
  TXT_CAMG_DOESNT_EXIST      ,"CAMG-chunk does not exist",
  TXT_IMAGINE_COMPRESSION    ,"'Imagine'-compression",
  TXT_MASKING_S 	     ,"Masking: %s",
  TXT_TRANSPARENT_COLOR      ,"transparent color",
  TXT_MASKPLANE 	     ,"additional mask-plane",
  TXT_LASSOMASK 	     ,"lasso-mask",
  TXT_ASPECT_DD 	     ,"Aspect: %d:%d",
  TXT_PAGESIZE_DD	     ,"Pagesize: %dx%d",
  TXT_LOADING_ILBM	     ,"Loading ILBM - picture",
  TXT_LOADING_ILBM_PBM	     ,"Loading ILBM-PBM - picture",
  TXT_SAVING_ILBM	     ,"Saving as ILBM - picture",
  TXT_COLOR_D_DDD	     ,"Color %3d: %3d %3d %3d\n",
  TXT_MORE_REGS_THAN_COLORS  ,"Enough color-registers available.",
  TXT_BUILDING_HISTOGRAMM    ,"Building color-histogramm.",
  TXT_D_DIFFERENT_COLORS     ,"%d different colors found.",
  TXT_SCANNING_CUBE	     ,"Scanning color-cube.",
  TXT_BITMAP_TO_CLUT	     ,"Converting bitmap to color-lookup-bitplanes.",
  TXT_BITMAP_TO_HAM	     ,"Converting bitmap to HAM-bitplanes.",
  TXT_CLUT_TO_24BIT	     ,"Converting CLUT-bitmap to 24bit.",
  TXT_LOADING_RGBN8	     ,"Loading RGBN/RGB8 - picture",
  TXT_GEM_IMAGE 	     ,"GEM Image (IMG)",
  TXT_PATTERNLENGTH_D	     ,"Pattern length: %d",
  TXT_PIXELWIDTH_D_YM	     ,"Pixel width: %d ym",
  TXT_PIXELHEIGHT_D_YM	     ,"Pixel height: %d ym",
  TXT_LOADING_IMG	     ,"Loading IMG - picture",
  TXT_PROGRESS_INDICATOR     ,"progress - indicator",
  TXT_OPERATION_MESSAGES     ,"operation - messages",
  TXT_CONVERSION_PROGRESS    ,"Conversion in progress...",
  TXT_LOAD		     ,"Load",
  TXT_INPUT_FORMAT	     ,"input format:",
  TXT_SAVE		     ,"Save",
  TXT_OUTPUT_FORMAT	     ,"output format:",
  TXT_SIZE		     ,"size",
  TXT_CUSTOM		     ,"custom",
  TXT_INTERPOLATED	     ,"interpolated",
  TXT_WIDTH		     ,"Width:",
  TXT_HEIGHT		     ,"Height:",
  TXT_TRANSFORM 	     ,"transform",
  TXT_FLIP		     ,"flip:",
  TXT_FLIP_NOTHING	     ,"not",
  TXT_FLIP_H		     ,"horizontal",
  TXT_FLIP_V		     ,"vertical",
  TXT_FLIP_HV		     ,"hor. & ver.",
  TXT_ROTATE		     ,"rotate",
  TXT_ROT_NOTHING	     ,"not",
  TXT_ROT_PLUS90	     ,"+90 degrees",
  TXT_ROT_MINUS90	     ,"-90 degrees",
  TXT_COLORS		     ,"colors",
  TXT_COLORMODE 	     ,"colormode:",
  TXT_COLORS_COL	     ,"colors:",
  TXT_DITHERING 	     ,"dithering:",
  TXT_DITHER_NONE	     ,"none",
  TXT_EFFECTS		     ,"effects:",
  TXT_EFX_NONE		     ,"none",
  TXT_EFX_BW		     ,"Black/White",
  TXT_EFX_INV		     ,"Inverse",
  TXT_EFX_INV_BW	     ,"Inverse & BW",
  TXT_EFX_RED_FILTER	     ,"Red filter",
  TXT_EFX_GREEN_FILTER	     ,"Green filter",
  TXT_EFX_BLUE_FILTER	     ,"Blue filter",
  TXT_EFX_YELLOW_FILTER      ,"Yellow filter",
  TXT_EFX_MAGENTA_FILTER     ,"Magenta filter",
  TXT_EFX_CYAN_FILTER	     ,"Cyan filter",
  TXT_BRIGHTNESS	     ,"brightness",
  TXT_CONTRAST		     ,"contrast",
  TXT_CONVERT		     ,"Convert",
  TXT_INFOS		     ,"Infos",
  TXT_WINDOW_TITLE	     ,"Picture format converter � by Dirk Farin",
  TXT_REDUCED_RESOLUTION     ,"    reduced resolution",
  TXT_MULTI_PAGE_PICTURE     ,"    multipage picture",
  TXT_TRANSPARENT_MASK	     ,"    transparency mask",
  TXT_NOTHING_SPECIAL	     ,"    nothing special",
  TXT_FULL_RES_PICTURE	     ,"picture with full resolution",
  TXT_REDU_RES_PICTURE	     ,"picture with reduced resolution",
  TXT_SINGLE_PAGE_PICTURE    ,"single page picture",
  TXT_UNCOMPRESSED	     ,"uncompressed",
  TXT_UNCOMPRESSED_WORDALIGN ,"uncompressed (word aligned)",
  TXT_MINSAMPLE_WHITE	     ,"MinSampleValue = White",
  TXT_MINSAMPLE_BLACK	     ,"MinSampleValue = Black",
  TXT_MINSAMPLE_RGB_DARK     ,"RGB MinSampleValue = Dark",
  TXT_PALETTE_COLOR	     ,"Palette Color",
  TXT_TRANSPARENCY_MASK      ,"Transparency Mask",
  TXT_BILEVEL		     ,"Bilevel picture",
  TXT_GREYSCALE_TO_BW	     ,"greyscale transformed to black/white",
  TXT_GREYSCALE_TO_BW_ERRDIF ,"greyscale transformed to black/white with error-diffusion",
  TXT_MSB_LSB		     ,"MSB to LSB",
  TXT_LSB_MSB		     ,"LSB to MSB",
  TXT_ORIENTATION_S	     ,"Orientation: first bitmap row is %s",
  TXT_EDGE_TLR		     ,"top edge, left to right",
  TXT_EDGE_TRL		     ,"top edge, right to left",
  TXT_EDGE_BRL		     ,"bottom edge, right to left",
  TXT_EDGE_BLR		     ,"bottom edge, left to right",
  TXT_EDGE_LTB		     ,"left edge, top to bottom",
  TXT_EDGE_RTB		     ,"right edge, top to bottom",
  TXT_EDGE_RBT		     ,"right edge, bottom to top",
  TXT_EDGE_LBT		     ,"left edge, bottom to top",
  TXT_PLANAR_NOBITPLANES     ,"no bitplanes (datas for each point together)",
  TXT_PLANAR_BITPLANES	     ,"bitplanes",
  TXT_4SPC_UNCOMPRESSED      ,"    uncompressed",
  TXT_4SPC_FILLBITSATEND     ,"    fill-bits inserted at end of line",
  TXT_4SPC_NONE 	     ,"    none",
  TXT_NO_INFORMATION	     ,"no information",
  TXT_NO_PREDICTION	     ,"no prediction",
  TXT_LOADING_TIFF_BW	     ,"Loading TIFF black/white - picture",
  TXT_LOADING_TIFF_256	     ,"Loading TIFF 256 colors - picture",
  TXT_LOADING_TIFF_16	     ,"Loading TIFF 16 colors - picture",
  TXT_LOADING_TIFF_BW_CCITT3 ,"Loading TIFF black/white, CCITT3-compressed picture",
  TXT_LOADING_TIFF_BW_PACKBIT,"Loading TIFF black/white, PackBit-compressed picture",
  TXT_LOADING_TIFF_256_PACKBIT,"Loading TIFF 256 colors, PackBit-compressed picture",
  TXT_LOADING_TIFF_LZW_RGB   ,"Loading TIFF LZW-compressed RGB picture",
  TXT_LOADING_TIFF_LZW_256   ,"Loading TIFF LZW-compressed 256 colors picture",
  TXT_LOADING_TIFF_LZW_MONO  ,"Loading TIFF LZW-compressed black/white picture",
  TXT_LOADING_TIFF_RGB	     ,"Loading TIFF uncompressed RGB picture",
  TXT_DOFLIP_H		     ,"Flipping picture horizontally",
  TXT_DOFLIP_V		     ,"Flipping picture vertically",
  TXT_TO_BW		     ,"Converting to black/white.",
  TXT_FILTERING 	     ,"Filtering colors.",
  TXT_INVERTING 	     ,"Inverting picture.",
  TXT_BRI_CON		     ,"Changing brightness and contrast.",
  TXT_RESIZING		     ,"Resizing picture.",
  TXT_INTERPOL_RESIZE	     ,"Resizing picture with interpolation.",
  TXT_ROTATING_90	     ,"Rotating picture 90 degrees.",
  TXT_ROTATING_M90	     ,"Rotating picture -90 degrees.",
  TXT_LOADREQ_TITLE	     ,"load file",
  TXT_SAVEREQ_TITLE	     ,"save file",
  TXT_REQUESTER_OK	     ,"OK",
  TXT_REQUESTER_CANCEL	     ,"cancel",
  TXT_SAVING_POSTSCRIPT      ,"saving to postscript file",
  TXT_POST_XPOS 	     ,"X-pos:",
  TXT_POST_YPOS 	     ,"Y-pos:",
  TXT_POST_WIDTH	     ,"Width:",
  TXT_POST_HEIGHT	     ,"Height:",
  TXT_POST_POSWIN_TITLE      ,"Specify position:",
  TXT_LOADING_JPEG	     ,"Loading JPEG (JFIF) picture",
  TXT_SAVING_JPEG	     ,"Saving JPEG (JFIF) picture",
  TXT_JPEG_QUALITY	     ,"Quality:",
  TXT_JPEG_PARAMETERS	     ,"JPEG output parameters",
  TXT_FAST_FLOYD	     ,"fast Floyd-Steinberg",
  TXT_COL_GRAYSCALE	     ,"grayscale",
  TXT_ABOUT		     ,"about prog.",
  TXT_UNREGISTERED	     ,"( unregistered ! )",
  TXT_DO_REGISTER_1	     ,"Do not forget to register",
  TXT_DO_REGISTER_2	     ,"this program !",
  TXT_LOADING_TARGA	     ,"Loading Targa picture",
  TXT_SAVING_GIF	     ,"Saving GIF picture",
  TXT_TARGA_INFOS	     ,"Targa picture infos",
  TXT_TARGA_NO_CMAP	     ,"no colomap in file",
  TXT_TARGA_CMAP_INCL	     ,"colormap included",
  TXT_TARGA_UNKN_CMAP	     ,"unknown type of colormap",
  TXT_TARGA_NO_IMAGE	     ,"no image in file",
  TXT_TARGA_UNCOMPR_CMAP     ,"uncompressed, colormap",
  TXT_TARGA_UNCOMPR_TRUECOL  ,"uncompressed, truecolor",
  TXT_TARGA_UNCOMPR_BW	     ,"uncompressed, black-white",
  TXT_TARGA_RLE_CMAP	     ,"RLE, colormap",
  TXT_TARGA_RLE_TRUECOL      ,"RLE, truecolor",
  TXT_TARGA_RLE_BW	     ,"RLE, black-white",
  TXT_TARGA_FIRST_CMAP_ENTRY ,"first colormap entry: %d",
  TXT_TARGA_CMAP_ENTRIES     ,"number of colormap entries: %d",
  TXT_TARGA_BITS_PER_ENTRY   ,"bits per colormap entry: %d",
  TXT_TARGA_XORIGIN	     ,"x origin: %d",
  TXT_TARGA_YORIGIN	     ,"y origin: %d",
  TXT_TARGA_WIDTH	     ,"width: %d",
  TXT_TARGA_HEIGHT	     ,"height: %d",
  TXT_TARGA_PIXELDEPTH	     ,"bits per pixel: %d",
  TXT_TARGA_BOTLEFT	     ,"bottom left",
  TXT_TARGA_BOTRIGHT	     ,"bottom right",
  TXT_TARGA_TOPLEFT	     ,"top left",
  TXT_TARGA_TOPRIGHT	     ,"top right",
  TXT_TARGA_ORIGIN	     ,"origin: %s",
  TXT_TARGA_ALPHA_BITS	     ,"bits for alpha-channel: %d",
  TXT_GRAPHIC_CONTROL_EXISTS	   , "Graphic Control Extension Block exists",
  TXT_GRAPHIC_CONTROL_CORRUPT	   , "Graphic Control-Block invalid",
  TXT_GRAPHIC_CONTROL_TRANSCOLOR_D , "transparent color: %d",

